### ISSUE TITLE
Information about making sprites

### ISSUE THREAD

**Issue by benwyatt2** [bradford-coderdojo/bltm#4]
So I've already made a bacon sprite for the BTLM game, but is there a link to the colour palette (for example, white is 7) so I can draw coloured sprites? Also, I don't mind about this one but is there anyway to increase the games tiles from 16x16 to 32x32?

**Comment by benwyatt2** [comment]
Sorry I mean increase the games tiles from 8x8 to 16x16

**Comment by xriss** [comment]
The palette along with text codes can be found in the sourcecode here

https://github.com/xriss/gamecake/blob/master/lua/wetgenes/gamecake/fun/bitdown.lua#L18

not the best documentation but should be a good start, at least it is a list of all the options.


As for size of every thing, sure, you can, but it is a big change and obviously all of the current images would need to be replaced and you would also need to choose between halfing the size of the level maps or doubling the screen resolution or you would need to switch to a scrolling map rather than a single screen.

If the screen resolution is changed then all of the speeds of the character movement and physics would then have to be reconsidered as they would probably be moving too fast.

So the answer is yes, but at the same time it is a restart from scratch decision when it comes to the design of everything so it is not just a simple change in one place, it is a small decision but one that effects everything else.

This is just the background characters and maps, Sprites can be any size of course, so things like the player or the pickups can easily be doubled in size and the map could just be made of many 8x8 chars stuck together to form other sizes.

Maybe if you tell us what you are trying to do we can suggest a way of doing it?

**Comment by notshi** [comment]
@benwyatt2 

Here's a simplified page for the colours https://bradford-coderdojo.github.io/bltm/fun-colours.html

**Comment by benwyatt2** [comment]
Thank you for sending me the links to the colour pallete.

I've increased the tile size by 2, tile map by 2 and screen resolution by 2. There's gaps between tiles but that's because I haven't made the new sprites so that can be fixed easily. However, the sprites are completely misaligned on the grid and move too fast, so that needs fixing.

**Comment by benwyatt2** [comment]
Here's the game itself, I wanted to increase the game by two because there's very little room for detail in an 8x8 sprite, and much more can be done with 16x16

https://xriss.github.io/fun64/run/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fbradford-coderdojo%2Fbltm%2Fmaster%2Fteam%2FBen%2FBaconGame.lua
